/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.Camion;
import model.Conductor;
import model.Usuario;
import service.RegistroService;

/**
 *
 * @author alb_9
 */
public class frmInformacion extends javax.swing.JFrame {

    /**
     * Creates new form frmInformación
     */
    public frmInformacion() {
        initComponents();
        
        setTitle("Ingreso de nuevo registro");
        setSize(1095, 400);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(0); // Se desactiva el cierre del programa con la X por defecto
        
    }
    
    private void limpiarDatos(){
        txtNickname.setText("");
        txtClave.setText("");
        txtNombre.setText("");
        txtLicencia.setText("");
        txtTelefono.setText("");
        
        txtMarca.setText("");
        txtModelo.setText("");
        txtAnio.setText("");
        txtKilometrajeTotal.setText("");
        
        cmbRol.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblNombreCompleto = new javax.swing.JLabel();
        lblLicencia = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtLicencia = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtKilometrajeTotal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lblNickname = new javax.swing.JLabel();
        txtNickname = new javax.swing.JTextField();
        lblClave = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        lblRol = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del conductor"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreCompleto.setText("Nombre completo");
        jPanel3.add(lblNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblLicencia.setText("Licencia");
        jPanel3.add(lblLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblCelular.setText("Celular");
        jPanel3.add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, -1));
        jPanel3.add(txtLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 190, -1));
        jPanel3.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 120, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 330, 210));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del camión"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMarca.setText("Marca");
        jPanel2.add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblModelo.setText("Modelo");
        jPanel2.add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblAnio.setText("Año");
        jPanel2.add(lblAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel2.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, -1));
        jPanel2.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, -1));
        jPanel2.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, -1));

        jLabel1.setText("Kilometraje total");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        jPanel2.add(txtKilometrajeTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 330, 300));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de usuario"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNickname.setText("Nombre usuario");
        jPanel4.add(lblNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        jPanel4.add(txtNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, -1));

        lblClave.setText("Contraseña");
        jPanel4.add(lblClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel4.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, -1));

        lblRol.setText("Rol del usuario");
        jPanel4.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "OPERADOR", "CONDUCTOR" }));
        jPanel4.add(cmbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel4.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 330, 210));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1095, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
        // Crear objetos desde los campos
        Usuario u = new Usuario(
            txtNickname.getText(),
            txtClave.getText(),
            cmbRol.getSelectedItem().toString()
        );

        Conductor c = new Conductor(
            txtNombre.getText(),
            txtLicencia.getText(),
            txtTelefono.getText()
        );

        Camion cam = new Camion(
            txtMarca.getText(),
            txtModelo.getText(),
            Integer.parseInt(txtAnio.getText()),
            Integer.parseInt(txtKilometrajeTotal.getText())
        );

        // Llamar al service
        RegistroService service = new RegistroService();
        service.registrarTodo(u, c, cam);

        JOptionPane.showMessageDialog(null, "Registro exitoso");
        
        // Limpiar TextField
        limpiarDatos();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInformacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblLicencia;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JLabel lblNombreCompleto;
    private javax.swing.JLabel lblRol;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtKilometrajeTotal;
    private javax.swing.JTextField txtLicencia;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNickname;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
