package view;

import service.RegistroMantenimientoService;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Conexion;
import java.sql.PreparedStatement;

public class frmMantenimiento extends javax.swing.JFrame {

    private int idMantenimientoSeleccionado = -1;

    public frmMantenimiento() {
        initComponents();

        java.awt.EventQueue.invokeLater(() -> {
            cargarTablaMantenimiento();
        });

        DefaultTableModel modelo = (DefaultTableModel) tblMantenimiento.getModel();
        modelo.setColumnIdentifiers(new Object[]{
            "ID",
            "Marca",
            "Modelo",
            "Tipo",
            "Descripción",
            "Fecha"
        });

        setSize(960, 580);
        setTitle("Registro de mantenimientos");
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(0);

        tblMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {

                int fila = tblMantenimiento.getSelectedRow();

                idMantenimientoSeleccionado = Integer.parseInt(
                        tblMantenimiento.getValueAt(fila, 0).toString()
                );

                cmbTipoMantenimiento.setSelectedItem(
                        tblMantenimiento.getValueAt(fila, 3).toString()
                );

                txtaDescripcion.setText(
                        tblMantenimiento.getValueAt(fila, 4).toString()
                );
            }
        });

    }

    public void cargarTablaMantenimiento() {

        String sql = "SELECT m.idMantenimiento, c.marca, c.modelo, m.tipoMantenimiento, m.descripcion, m.fecha "
                + "FROM mantenimiento m "
                + "JOIN camiones c ON m.idCamion = c.idCamion";

        try {
            Conexion con = new Conexion();
            Connection conexion = con.getConnection();

            PreparedStatement ps = conexion.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            DefaultTableModel modelo = (DefaultTableModel) tblMantenimiento.getModel();
            modelo.setRowCount(0);

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt("idMantenimiento"),
                    rs.getString("marca"),
                    rs.getString("modelo"),
                    rs.getString("tipoMantenimiento"),
                    rs.getString("descripcion"),
                    rs.getTimestamp("fecha")
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar tabla: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlTableMantenimiento = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMantenimiento = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblIdCamion = new javax.swing.JLabel();
        txtIdCamion = new javax.swing.JTextField();
        lblTipoMantenimiento = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaDescripcion = new javax.swing.JTextArea();
        btnRegistrar = new javax.swing.JButton();
        cmbTipoMantenimiento = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTableMantenimiento.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de mantenimientos\n"));
        pnlTableMantenimiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMantenimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMantenimiento);

        pnlTableMantenimiento.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jPanel1.add(pnlTableMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 560, 490));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Información"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdCamion.setText("ID Camión");
        jPanel2.add(lblIdCamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        jPanel2.add(txtIdCamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, -1));

        lblTipoMantenimiento.setText("Tipo mantenimiento");
        jPanel2.add(lblTipoMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblDescripcion.setText("Descripción");
        jPanel2.add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txtaDescripcion.setColumns(20);
        txtaDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtaDescripcion);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 176, 290, 130));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 90, -1));

        cmbTipoMantenimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MECANICO" }));
        jPanel2.add(cmbTipoMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 90, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 90, -1));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 90, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 330, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            // 1. Validaciones
            if (txtIdCamion.getText().isEmpty() || txtaDescripcion.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Complete los campos");
                return;
            }

            int idCamion = Integer.parseInt(txtIdCamion.getText());
            String tipo = cmbTipoMantenimiento.getSelectedItem().toString();
            String descripcion = txtaDescripcion.getText();

            // 2. Llamar al service
            RegistroMantenimientoService service = new RegistroMantenimientoService();
            service.registrarMantenimiento(idCamion, tipo, descripcion);

            JOptionPane.showMessageDialog(null, "Mantenimiento registrado correctamente");

            // 3. Refrescar tabla
            cargarTablaMantenimiento();

            // 4. Limpiar campos
            txtIdCamion.setText("");
            txtaDescripcion.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ID debe ser numérico");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (idMantenimientoSeleccionado == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro");
            return;
        }

        String tipo = cmbTipoMantenimiento.getSelectedItem().toString();
        String descripcion = txtaDescripcion.getText();

        RegistroMantenimientoService service = new RegistroMantenimientoService();
        service.actualizarMantenimiento(idMantenimientoSeleccionado, tipo, descripcion);

        JOptionPane.showMessageDialog(null, "Actualizado correctamente");

        cargarTablaMantenimiento();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (idMantenimientoSeleccionado == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(null,
                "¿Eliminar este mantenimiento?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {

            RegistroMantenimientoService service = new RegistroMantenimientoService();
            service.eliminarMantenimiento(idMantenimientoSeleccionado);

            JOptionPane.showMessageDialog(null, "Eliminado correctamente");

            cargarTablaMantenimiento();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbTipoMantenimiento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblIdCamion;
    private javax.swing.JLabel lblTipoMantenimiento;
    private javax.swing.JPanel pnlTableMantenimiento;
    private javax.swing.JTable tblMantenimiento;
    private javax.swing.JTextField txtIdCamion;
    private javax.swing.JTextArea txtaDescripcion;
    // End of variables declaration//GEN-END:variables
}
