package view;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Conexion;
import java.sql.PreparedStatement;
import service.RegistroKilometrajeService;

public class frmRegistro extends javax.swing.JFrame {

    public frmRegistro() {
        initComponents();
        
        java.awt.EventQueue.invokeLater(() -> {
            cargarTabla();
            
        });
        DefaultTableModel modelo = (DefaultTableModel) tblRegistros.getModel();
        modelo.setColumnIdentifiers(new Object[]{
            "ID Registro",
            "Marca",
            "Modelo",
            "KM Recorrido",
            "Fecha"
        });

        DefaultTableModel modeloC = (DefaultTableModel) tblCamiones.getModel();
        modeloC.setColumnIdentifiers(new Object[]{
            "ID Camión",
            "Marca",
            "Modelo",
            "KM Total"
        });
        java.awt.EventQueue.invokeLater(() -> {
            cargarCamiones();
        });

        setTitle("Registro");
        setSize(1060, 600);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(0); // Se desactiva el cierre del programa con la X por defecto

    }

    public void salir() {
        int opSalir = JOptionPane.showConfirmDialog(this, "Estás seguro que deseas salir?", "Salir", 0); //El cero indica que el usuario elige salir
        if (opSalir == 0) {
            System.exit(0);
        }
    }

    public void cargarTabla() {

        String sql = "SELECT r.idRegistro, c.marca, c.modelo, r.kilometrajeRecorrido, r.fechaRegistro "
                + "FROM registroKilometraje r "
                + "JOIN camiones c ON r.idCamion = c.idCamion";

        try {
            Conexion con = new Conexion();
            Connection conexion = con.getConnection();

            PreparedStatement ps = conexion.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            DefaultTableModel modelo = (DefaultTableModel) tblRegistros.getModel();
            modelo.setRowCount(0); // limpiar tabla

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt("idRegistro"),
                    rs.getString("marca"),
                    rs.getString("modelo"),
                    rs.getInt("kilometrajeRecorrido"),
                    rs.getTimestamp("fechaRegistro")
                });
            }

            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar tabla: " + e.getMessage());
            e.printStackTrace();
        }

    }

    public void cargarCamiones() {

        String sql = "SELECT idCamion, marca, modelo, kilometrajeTotal FROM camiones";

        try {
            Conexion con = new Conexion();
            Connection conexion = con.getConnection();

            PreparedStatement ps = conexion.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            DefaultTableModel modelo = (DefaultTableModel) tblCamiones.getModel();
            modelo.setRowCount(0);

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt("idCamion"),
                    rs.getString("marca"),
                    rs.getString("modelo"),
                    rs.getInt("kilometrajeTotal")
                });
            }

            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        pnlRegistros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistros = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCamiones = new javax.swing.JTable();
        pnlDatosCamion = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        txtIDCamion = new javax.swing.JTextField();
        lblKm = new javax.swing.JLabel();
        txtKm = new javax.swing.JTextField();
        btnGrabar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCrearRegistro = new javax.swing.JButton();
        btnRegistrarMantenimiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRegistros.setBorder(javax.swing.BorderFactory.createTitledBorder("Registros"));
        pnlRegistros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRegistros);

        pnlRegistros.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 680, 200));

        tblCamiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblCamiones);

        pnlRegistros.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 247, 680, 220));

        pnlDatos.add(pnlRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 730, 490));

        pnlDatosCamion.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Camión"));
        pnlDatosCamion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID.setText("ID Camión");
        pnlDatosCamion.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtIDCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDCamionActionPerformed(evt);
            }
        });
        pnlDatosCamion.add(txtIDCamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, -1));

        lblKm.setText("Kilometraje (sólo números)");
        pnlDatosCamion.add(lblKm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtKm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKmActionPerformed(evt);
            }
        });
        txtKm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKmKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKmKeyTyped(evt);
            }
        });
        pnlDatosCamion.add(txtKm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, -1));

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        pnlDatosCamion.add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        pnlDatos.add(pnlDatosCamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 260, 180));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlDatos.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 170, 40));

        btnCrearRegistro.setText("Crear nuevo registro");
        btnCrearRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearRegistroActionPerformed(evt);
            }
        });
        pnlDatos.add(btnCrearRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 170, 40));

        btnRegistrarMantenimiento.setText("Registrar mantenimiento");
        btnRegistrarMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMantenimientoActionPerformed(evt);
            }
        });
        pnlDatos.add(btnRegistrarMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 1059, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDCamionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDCamionActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        try {
            // Validaciones
            if (txtIDCamion.getText().isEmpty() || txtKm.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Complete todos los campos");
                return;
            }

            int idCamion = Integer.parseInt(txtIDCamion.getText());
            int km = Integer.parseInt(txtKm.getText());

            if (km <= 0) {
                JOptionPane.showMessageDialog(null, "Kilometraje inválido");
                return;
            }

            // Llamar al service
            RegistroKilometrajeService service = new RegistroKilometrajeService();
            service.registrarKilometraje(idCamion, km);

            // Refrescar tabla
            cargarTabla();
            cargarCamiones();

            // Limpiar campos
            txtIDCamion.setText("");
            txtKm.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese números válidos");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        salir();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtKmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKmKeyReleased
        // Elimina caracteres que no sean números
        String limpio = txtKm.getText().replaceAll("[^0-9]", "");

        // Limita el máximo a 6 números aunque los peguen
        if (limpio.length() > 6) {
            limpio = limpio.substring(0, 6);
        }
    }//GEN-LAST:event_txtKmKeyReleased

    private void txtKmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKmKeyTyped
        // Restringe el txtStock a sólo recibir números
        char tecla = evt.getKeyChar();
        if (tecla < '0' || tecla > '9') {
            evt.consume();
        }

        // Restringe al txtKm a recibir un máximo de 4 dígitos
        if (txtKm.getText().length() >= 6) {
            evt.consume();
        }

        // Restringe el uso del espacio dentro del txtStock
        if (Character.isWhitespace(tecla)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtKmKeyTyped

    private void btnCrearRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearRegistroActionPerformed
        frmInformacion objInformacion = new frmInformacion();
        objInformacion.setVisible(true);
    }//GEN-LAST:event_btnCrearRegistroActionPerformed

    private void txtKmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKmActionPerformed

    private void btnRegistrarMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMantenimientoActionPerformed
        frmMantenimiento objMant = new frmMantenimiento();
        objMant.setVisible(true);
    }//GEN-LAST:event_btnRegistrarMantenimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearRegistro;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnRegistrarMantenimiento;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblKm;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlDatosCamion;
    private javax.swing.JPanel pnlRegistros;
    private javax.swing.JTable tblCamiones;
    private javax.swing.JTable tblRegistros;
    private javax.swing.JTextField txtIDCamion;
    private javax.swing.JTextField txtKm;
    // End of variables declaration//GEN-END:variables
}
